### PR TITLE
Edits on several documentation pages.

### PR DESCRIPTION
**Pull request by coalpha**
Mostly on How-to-Setup.
Maybe think about renaming to "installation-instructions"?

### CODE REVIEW

**Review by koumaza — APPROVED** [review]
LGTM. I've checked all the files in the commit and it's great.

**Comment by koumaza** [comment]
> Mostly on How-to-Setup.
> Maybe think about renaming to "installation-instructions"?

I think that Setup and Install have the same meaning, but since Setup can contain Install.
I think that How2Setup is good for the title, and installation-instructions is good for Markdown Heading.

**Review by yuk7 — COMMENTED** [review]
Thank you!
I think it's generally good.

But personally, I don't want to link directly from the ArchWSL documentation to the wsldl source code.
It's a different project and the source code is subject to change.

I think you should mention it in the wsldl documentation and link to it.

**Comment by yuk7** [comment]
> > Mostly on How-to-Setup.
> > Maybe think about renaming to "installation-instructions"?
> 
> I consider that Setup and Install have the same meaning, but since Setup can contain Install.
> so I think that How2Setup is good for the title, and installation-instructions is good for Markdown Heading.

I agree with this too.

**Comment by coalpha** [comment]
Ok. I will update `How-to-Setup.md` to make sure the headers match and I'll move the reference to `wsldl/main.c` into the `wsldl-pg/docs` repository.

**Pull request closed without merging**
