### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by 7k5x**
Are there any errors in _include that I mistyped?

### CODE REVIEW

**Comment by 7k5x** [comment]
I don’t want to merge this prematurely, since I could have erred in the HTML file.

**Review by yuk7 — APPROVED** [review]
Ok!
I don't think there are problems.

**Comment by yuk7** [comment]
I reviewed it, I didn't find any problems.

**Comment by yuk7** [comment]
merged to main.
Thank you so much!

**Pull request merged**
